Repository square/eslint-plugin-square, pull requests merged in 2020-03, with the labels that each got.

#2 docs: add NPM badge to README
  README.md
Labels: documentation

#6 Add `typescript` config
  README.md
  lib/config/typescript.js
  lib/index.js
  package.json
  yarn.lock
Labels: enhancement

#16 chore(dev-deps): add release-it-lerna-changelog
  package.json
  yarn.lock
Labels: dependencies
