Repository square/eslint-plugin-square, pull requests merged in 2020-05, with the labels that each got.

#40 Move `sort-vars` to `base` config
  lib/config/base.js
  lib/config/react.js
  lib/config/typescript.js
Labels: breaking

#42 Enforce kebab-case filenames in `base` configuration
  lib/config/base.js
  lib/config/ember.js
  lib/config/react.js
  lib/config/typescript.js
Labels: breaking

#62 Enable `catchRouterMicrolib` option on `ember/no-private-routing-service` rule
  lib/config/ember.js
Labels: breaking

#41 Enable eslint-plugin-unicorn recommended rules in `base` config
  .eslintrc.js
  README.md
  lib/config/base.js
  package.json
Labels: breaking

#64 Update to eslint 7 internally
  .eslintrc.js
  .github/workflows/ci.yml
  lib/rules/no-test-return-value.js
  lib/rules/use-call-count-test-assert.js
  package.json
  yarn.lock
Labels: dependencies, internal

#80 Add new rule `no-restricted-files`
  README.md
  docs/rules/no-restricted-files.md
  lib/index.js
  lib/rules/no-restricted-files.js
  tests/lib/rules/no-restricted-files.js
Labels: enhancement

#88 Handle TypeScript files with `no-missing-tests` rule
  docs/rules/no-missing-tests.md
  lib/rules/no-missing-tests.js
  lib/utils/flat.js
  tests/lib/rules/use-call-count-test-assert.js
Labels: bug
