Repository square/eslint-plugin-square, pull requests merged in 2020-04, with the labels that each got.

#22 Add `react` configuration
  README.md
  lib/config/react.js
  lib/index.js
  package.json
  yarn.lock
Labels: enhancement

#24 Mention the criteria that rules should meet to be enabled in our configurations
  README.md
Labels: documentation

#25 Allow PascalCase component filenames in `react` config
  lib/config/react.js
Labels: bug

#26 Widen dependency range for eslint-plugin-prettier
  package.json
  yarn.lock
Labels: dependencies

#28 Disable `no-useless-constructor` rule in `typescript` config
  lib/config/typescript.js
Labels: bug

#27 Tweak filename regexes and other rules in `react` config
  lib/config/react.js
Labels: bug

#29 Switch from release-it to lerna-changelog
  RELEASE.md
  package.json
  yarn.lock
Labels: dependencies

#31 Add tests to ensure configs are exported and mentioned in README
  tests/config-setup.js
Labels: internal

#30 Standardize filename regexes
  lib/config/ember.js
  lib/config/react.js
  lib/config/typescript.js
  lib/utils/filenames.js
  tests/lib/utils/filenames.js
Labels: internal

#32 Update each rule doc to mention what config enables the rule
  README.md
  docs/rules/no-assert-ok-find.md
  docs/rules/no-focused-tests.md
  docs/rules/no-lazy-arrow-functions.md
  docs/rules/no-test-expect-assertion-count.md
  docs/rules/no-test-return-value.md
  docs/rules/no-translation-key-interpolation.md
  docs/rules/require-await-function.md
  docs/rules/use-call-count-test-assert.md
  docs/rules/use-ember-find.md
  tests/rule-setup.js
Labels: documentation

#39 Kebab-case filename restrictions should allow single-character filenames
  lib/utils/filenames.js
  tests/lib/utils/filenames.js
Labels: bug

#38 Export filename regex utils
  lib/index.js
Labels: bug

#49 Update warning for unused-vars in Typescript
  lib/config/typescript.js
Labels: bug

#57 Begin testing under Node 14
  .github/workflows/ci.yml
Labels: internal
