Repository square/eslint-plugin-square, pull requests merged in 2022-08, with the labels that each got.

#702 Handle `.d.ts` files correctly for `filenames/match-exported` rule
  lib/config/base.js
Labels: bug

#718 Mention lint scripts and ways to run linting in README
  README.md
Labels: documentation

#719 Mention that this needs to be installed alongside our peer dependency ESLint in README
  README.md
Labels: documentation

#723 Add TypeScript type-checking to all JavaScript files and publish utility types
  .eslintrc.js
  .gitignore
  lib/rules/no-assert-ok-find.js
  lib/rules/no-handlebar-interpolation.js
  lib/rules/no-missing-tests.js
  lib/rules/no-restricted-files.js
  lib/rules/no-test-return-value.js
  lib/rules/no-translation-key-interpolation.js
  lib/rules/require-await-function.js
  lib/rules/use-call-count-test-assert.js
  lib/rules/use-ember-find.js
  lib/utils/get-parent-function-node.js
  lib/utils/import.js
  lib/utils/is-identifier.js
  lib/utils/is-literal.js
  lib/utils/is-member-expression.js
  lib/utils/is-string-literal.js
  lib/utils/is-test-file.js
  lib/utils/is-test-hook.js
  package.json
  tests/helpers/babel-eslint-parser.js
  tests/helpers/faux-context.js
  tests/lib/rules/use-call-count-test-assert.js
  tests/lib/utils/imports.js
  tests/lib/utils/is-literal.js
  tests/rule-setup.js
  tsconfig.json
  types/global.d.ts
  yarn.lock
Labels: enhancement
