Repository square/eslint-plugin-square, pull requests merged in 2022-07, with the labels that each got.

#676 Drop support for Node 12 and Node 17
  .github/workflows/ci.yml
  README.md
  package.json
Labels: breaking

#675 Drop support below ESLint 8.18.0
  README.md
  package.json
Labels: breaking

#693 Enable `unicorn/prefer-node-protocol` rule internally
  .eslintrc.js
  lib/config/base.js
  lib/rules/no-missing-tests.js
  lib/utils/import.js
  tests/config-setup.js
  tests/lib/rules/no-missing-tests.js
  tests/lib/utils/filenames.js
  tests/lib/utils/imports.js
  tests/lib/utils/is-literal.js
  tests/lib/utils/is-test-file.js
  tests/rule-setup.js
Labels: internal

#691 Remove `filenames/match-regex` rule in favor of `unicorn/filename-case`
  lib/config/base.js
  lib/config/react.js
  lib/index.js
  lib/utils/filenames.js
  tests/lib/utils/filenames.js
Labels: breaking

#674 Expect pascal-case export for components in `React` config
  lib/config/react.js
Labels: bug

#698 Allow placeholder addon types file generated by ember-cli-typescript blueprint
  lib/config/ember.js
Labels: bug
